name: CI Pipeline - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Java (for a Java-based project, adjust if needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Cache dependencies to speed up the process
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Maven build and tests
      - name: Run Maven build and tests
        run: mvn clean install

      # Step 5: Upload test results (optional, for tracking)
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/test-classes
